# syntax=docker/dockerfile:1@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89

# base
FROM python:3.13.14@sha256:4c822f0fadfeba9ea973d81fb5bbd5c2106f12ae02d0a5cdd48907909395310b as base
RUN apt update && \
    apt install dbus python-dbus-dev build-essential libssl-dev libffi-dev python3-dev -y --no-install-recommends  \
    && rm -rf /var/lib/apt/lists/*

ENV CARGO_NET_GIT_FETCH_WITH_CLI=true


FROM base AS builder
COPY requirements_mod.txt ./requirements.txt

#COPY ./artifacts/ /wheelartifacts
#ARG TARGETOS
#ARG TARGETVARIANT
#ARG TARGETARCH
#RUN find /wheelartifacts -mindepth 2 -maxdepth 2 -regextype posix-extended -type d -not -regex  ".*/${TARGETOS}_${TARGETARCH}(_${TARGETVARIANT})?$" -exec rm -rv {} \; \
#    && mv /wheelartifacts/*/*/wheels/* /wheelartifacts || true \
#    && du -a /wheelartifacts 
# Build dependencys as wheels

#RUN --mount=type=bind,target=/wheelartifacts,source=artifacts,rw \
#    find /wheelartifacts -mindepth 2 -maxdepth 2 -regextype posix-extended -type d -not -regex  ".*/${TARGETOS}_${TARGETARCH}(_${TARGETVARIANT})?$" -exec rm -rv {} \; \
#    && mv /wheelartifacts/*/*/wheels/* /wheelartifacts || true \
#    && du -a /wheelartifacts \

ARG PKGS=python3-dev
ARG CRYPTOGRAPHY_DONT_BUILD_RUST=1
RUN apt update && \
    apt install $PKGS -y --no-install-recommends  \
    && rm -rf /var/lib/apt/lists/*

RUN pip wheel --no-cache --wheel-dir /wheels \
#    --find-links file:///wheelartifacts \
    -r requirements.txt


FROM scratch AS image-stage
COPY --from=builder /wheels ./wheels
COPY --from=builder requirements.txt ./


# Just a stage to export our wheel 
FROM scratch AS export-stage
COPY --from=builder /wheels ./wheels
COPY --from=builder requirements.txt ./
