name: 'Build an run integrationtests'
description: 'Build multi stage docker image and run integrationtests'
inputs:
  PLATTFORM:  
    description: 'Plattform for which to build the image, only a single plattform can be specified here'
    required: false
    default: 'linux/amd64'
  FHEMPY_VERSION:  
    description: 'Which Version of FHMEPY is used, this will be passed as build argument'
    required: true
    default: '0.1.487'
    
runs:
  using: "composite"
  steps: 
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-base
        uses: docker/metadata-action@v4.0.1
        with:
          images: base

      - name: Cache wheels 
        id: cache-wheels
        uses: actions/cache@v3
        with:
          path: .cache/wheels
          key: wheels
      
      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: .cache/pip
          key: pip

      - name: Build base image
        uses: docker/build-push-action@v3.2.0
        id: docker_build_base
        with:
          context: .
          platforms: ${{ inputs.PLATTFORM }}
          push: false
          load: false
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          cache-to: type=gha,mode=max,scope=verify_base_${{ inputs.PLATTFORM }}
          cache-from: type=gha,scope=verify_base_${{ inputs.PLATTFORM }}
          build-args: FHEMPY_V=${{ inputs.FHEMPY_VERSION }}
          target: export-stage
          outputs: type=local,dest=./cache
            

      - name: Extract Docker metadata
        id: meta-runtime
        uses: docker/metadata-action@v4.0.1
        with:
          images: runtime

      - name: Build for integration test amd64 
        uses: docker/build-push-action@v3.2.0
        id: docker_build_runtime
        with:
          context: .
          platforms: ${{ inputs.PLATTFORM }}
          push: false
          load: true
          tags: ${{ steps.meta-runtime.outputs.tags }}
          labels: ${{ steps.meta-runtime.outputs.labels }}
          cache-from: | 
            type=gha,scope=verify_base_${{ inputs.PLATTFORM }}
            type=gha,scope=verify_runtime_${{ inputs.PLATTFORM }}
          cache-to: type=gha,mode=max,scope=verify_runtime_${{ inputs.PLATTFORM }}
          build-args: FHEMPY_V=${{ inputs.FHEMPY_VERSION }}
          target: runtime

      - name: Run integration tests
        shell: bash
        run: |
          ./scripts/test-integration.sh ${{ fromJSON(steps.meta-runtime.outputs.json).tags[0] }}

      - name: list files
        shell: bash
        run: |
          ls -R ./cache
