name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'fhempy/fhempy'

      #- name: download fhempy
      #- run: |
      #  pip download 

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.1
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          CIBW_ARCHS_LINUX: aarch64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
