name: Docker-verify
on:
  schedule:
    - cron: '45 4 * * *'
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - 'releases/**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    #permissions:
      # contents: write
      #packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      #id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Split fhempy Version
        id: split_fhempyV
        run: |
          echo "result=$(grep '^fhempy' requirements.txt | cut -d '=' -f3)" >> $GITHUB_OUTPUT
      
      - name: Find image strings
        id: extract_image
        run: |
           echo "image_name=$(grep -m 1 '^FROM' Dockerfile | cut -d ' ' -f2 | cut -d ':' -f1)" >> $GITHUB_OUTPUT
           echo "image_version=$(grep -m 1 '^FROM' Dockerfile | cut -d ' ' -f2 | cut -d ':' -f2)" >> $GITHUB_OUTPUT

      - name: Cache wheels 
        id: cache-wheels
        uses: actions/cache@v3
        with:
          path: ./cache/wheels
          key: wheels-${{ steps.split_fhempyV.outputs.result}}
          restore-keys: |
            whells-
            c-wheels-
      
      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ./cache/pip
          key: pip-${{ steps.split_fhempyV.outputs.result}}
          restore-keys: |
            pip
            c-pip
     
      - name: Build image and run integrationtests (amd64)
        id: build_and_run_integrationtests
        uses: ./.github/actions/integrationtest
        with:
           PLATTFORM: linux/amd64
           FHEMPY_VERSION: ${{ steps.split_fhempyV.outputs.result }}
