name: Matrix-build-wheels

on:
  push:
    branches:
#      - main
      - 'releases/**'


jobs:
  prepare_build:
#    name: Get fhempy version
    runs-on: ubuntu-latest
    outputs:
      fhempyV: ${{steps.split_fhempyV.outputs.result}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Split fhempy Version
        id: split_fhempyV
        run: |
          echo "result=$(grep '^fhempy' requirements.txt | cut -d '=' -f3)" >> $GITHUB_OUTPUT      
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build builder stage
        id: build_base_cross
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: Dockerfile.wheels
          platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7
          push: false
          target: base
          cache-to: type=gha,mode=max,scope=base_stage_cross
          cache-from: |
            type=gha,scope=base_stage_cross
          build-args: FHEMPY_V=${{ steps.split_fhempyV.outputs.result}}

  prepare_matrix:
#    name:  Find fhempy modules 
    needs: prepare_build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.getModules.outputs.matrix}}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'fhempy/fhempy'
          ref: 'v${{ needs.prepare_build.outputs.fhempyV }}'

      - name: Get module name and prepare matrix
        id: getModules
        working-directory: FHEM/bindings/python/fhempy/lib
        run: |
          MODS=($(find ./ -type f -name manifest.json -exec sh -c 'dirname {}' \;  | sed 's|^./||'))
          #printf '%s\n' "${MODS[@]}"
          
          JSON='{ "include":[] }'
          for i in "${MODS[@]}"
          do
              REQS=$(jq -cr 'select(.requirements != []).requirements' ./"$i"/manifest.json)
              if [[ -n $REQS && $i == @(tuya*|core*|google_weather) ]]; then 
                JSON=$(echo $JSON | jq -c --argjson REQUIREMENTS $REQS --arg M "$i" '.include += [{"module": $M, "requirements": $REQUIREMENTS}]')
              fi
          done
          #echo $JSON
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

  buildwWeels:
    runs-on: ubuntu-latest
    needs: [prepare_build, prepare_matrix]
    strategy:
      max-parallel: 2
      matrix:
        ${{fromJson(needs.prepare_matrix.outputs.matrix)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: check variables
        run: |
          echo '${{ toJSON(matrix) }}'

      - name: overwrite requirement for mod
        run: |
          echo '${{toJSON(matrix.requirements)}}'  | jq --raw-output -e '.[]' > ./requirements.txt
          cat ./requirements.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image with Buildx (don't push if it is not a release)
      # https://github.com/docker/build-push-action
      - name: Build wheels 
        id: build_base_cross
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: Dockerfile.wheels
          platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7
          push: false
          target: export-stage
          outputs: type=local,dest=./wheelhouse
          cache-from: |
            type=gha,scope=base_stage_cross
          build-args: FHEMPY_V=${{ needs.prepare_build.outputs.fhempyV }}

      #- name: list files in wheelhouse
      #  run: |
      #    du -a ./wheelhouse

      - name: upload wheels as artifact for module ${{matrix.module}}
        uses: actions/upload-artifact@v3
        with: 
          name: ${{matrix.module}}
          path: |
            ./wheelhouse/*/wheels
            ./wheelhouse/*/requirements.txt

    

  buildfhempy:
    needs: [prepare_build, buildwWeels]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
    outputs:
      imageid: ${{ steps.docker_build_runtime_cross.outputs.imageid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find image String
        id: extract_image
        run: |
           echo "image_name=$(grep -m 1 '^FROM' Dockerfile | cut -d ' ' -f2 | cut -d ':' -f1)" >> $GITHUB_OUTPUT
           echo "image_version=$(grep -m 1 '^FROM' Dockerfile | cut -d ' ' -f2 | cut -d ':' -f2)" >> $GITHUB_OUTPUT
      
      - name: Update docs
        if: ${{ github.event_name == 'release' }}
        run: |
            sed -e "s/{FHEMPY_VERSION}/${{ needs.prepare_build.outputs.fhempyV }}/" -e "s/{PYTHON_VERSION}/${{ steps.extract_image.outputs.image_version}}/" -e "s/{DEBIAN_RELEASE}/buster/" -e s/{IMAGE_TAG}/${{ github.ref_name }}/ < README.tmpl > README.md

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name == 'release'
        uses: sigstore/cosign-installer@v2.8.1
        with:
          cosign-release: 'v1.9.0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: fetch our artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./wheelhouse/

      - name: list files in wheel Cache before running a build
        run: |
          du -a ./wheelhouse/

      - name: Build image and run integrationtests (amd64)
        id: build_and_run_integrationtests
        uses: ./.github/actions/integrationtest
        with:
           PLATTFORM: linux/amd64
           FHEMPY_VERSION: ${{ needs.prepare_build.outputs.fhempyV }}

      # Login against a Docker registry if it is a release
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        #if: github.event_name == 'release'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push if it is not a release)
      # https://github.com/docker/build-push-action
      - name: Build base image for all plattforms
        id: build_base_cross
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: FHEMPY_V=${{ needs.prepare_build.outputs.fhempyV }}
          target: base

      #- name: list files in wheel Cache
      #  run: |
      #    du -a ./wheelhouse

      - name: Build and push Docker image for all plattforms
        uses: docker/build-push-action@v3.2.0
        id: docker_build_runtime_cross
        with:
          context: .
          platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7
          push: true # ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: | 
            type=gha,scope=verify_runtime_linux/amd64
            type=gha,scope=publish_runtime_cross
          cache-to: type=gha,mode=max,scope=publish_runtime_cross
          build-args: FHEMPY_V=${{ needs.prepare_build.outputs.fhempyV }}
          target: runtime

      - name: show image details
        run: | 
          echo ${{ steps.docker_build_runtime_cross.outputs.imageid }}
          echo ${{ steps.docker_build_runtime_cross.outputs.digest }}
      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name == 'release' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.docker_build_runtime_cross.outputs.digest }}
      
      - name: git commit README.md 
        id: commit
        if: ${{ github.event_name == 'release' }}
        run: |
          git config --global user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "README.md: Update Versions" -a && echo "::set-output name=status::true" || true
      
      - name: Push back to protected branch (main)
        uses: CasperWA/push-protected@v2
        if: ${{ github.event_name == 'release' }}
        with:
          token: ${{ secrets.BOT_PUSH_TOKEN }}
          branch: main
          #unprotect_reviews: true

  run-container:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    
    needs: [buildfhempy,prepare_build]
    # Service containers to run with `container-job`
    services:
      fhem: 
        image: ghcr.io/fhem/fhem/fhem-minimal-docker:3-bullseye
        ports:
          - 8083:8083
        volumes:
          - ${{ github.workspace }}/opt/fhem:/opt/fhem
        options: >-
          -e CPAN_PKGS="Protocol::WebSocket"

          
      fhempy:
        image:  ghcr.io/fhem/fhempy-docker@${{ needs.buildfhempy.outputs.imageid }}
     #   image:  ghcr.io/fhem/fhempy-docker:releases-1.3-beta

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'fhempy/fhempy'
          ref: 'v${{ needs.prepare_build.outputs.fhempyV }}'
          path: fhempy


      - name: copy perl Modules to fhem volume directory
        run: |
          sudo cp ./fhempy/FHEM/*.pm ${{ github.workspace }}/opt/fhem/FHEM

      - name: install fhemcl tool
        run: |
          wget -O fhemcl.sh https://raw.githubusercontent.com/heinz-otto/fhemcl/master/fhemcl.sh
          chmod +x fhemcl.sh

      
      - name: test googleweather
        run: |
          echo "::group::Install Modules"
          echo -e "reload 10_fhempy" | ./fhemcl.sh http://localhost:8083
          echo -e "reload 10_BindingsIo" | ./fhemcl.sh http://localhost:8083
          echo "::endgroup::"

          echo "::group::Define fhempy"          
          echo -e "define fhempy_peer_IP BindingsIo fhempy:15733 fhempy" | ./fhemcl.sh http://localhost:8083
          echo -e "list  fhempy_peer_IP" | ./fhemcl.sh http://localhost:8083
          sleep 7
          echo "::endgroup::"

          echo "::group::Define google_weather"          
          echo -e "define my_weather fhempy google_weather frankfurt" | ./fhemcl.sh http://localhost:8083
          sleep 10
          echo -e "list my_weather" | ./fhemcl.sh http://localhost:8083
          echo "::endgroup::"
